version: '3'
services:

  admin:
    image: cpatrut/authorization-server
    ports:
     - "8080:8080"
    depends_on:
      - db
  authorization-server-db:
    image: postgres:9.5
    ports:
     - "5432:5432"