version: '3'
services:

  authorization-server:
    build: .
    ports:
     - "8080:8080"
    depends_on:
      - authorization-server-db
  authorization-server-db:
    image: postgres:9.5
    ports:
     - "5432:5432"